/**
 * WADJET GRC — Enterprise Report Engine
 * 
 * Board-quality reports with executive summaries, KPI cards,
 * professional formatting, and clear visual hierarchy.
 */

import ExcelJS from "exceljs";
import { PDFDocument, rgb, StandardFonts, degrees } from "pdf-lib";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export const BRANDING = {
  logoPath: path.resolve(__dirname, "../public/logo.png"),
  primaryColorHex: "#D4AF37",
  secondaryColorHex: "#141417",
  watermarkText: "WADJET GRC — CONFIDENTIAL",
  footerText: "Generated by WADJET GRC Platform",
};

function hexToRgb(hex) {
  const h = hex.replace("#", "");
  return rgb(parseInt(h.slice(0, 2), 16) / 255, parseInt(h.slice(2, 4), 16) / 255, parseInt(h.slice(4, 6), 16) / 255);
}

const PRIMARY = hexToRgb(BRANDING.primaryColorHex);
const PRIMARY_HEX = BRANDING.primaryColorHex.replace("#", "");
const DARK_BG = rgb(0.1, 0.1, 0.12);

const RISK_COLORS = {
  Critical: { bg: "FFFDE8E8", fg: "FFC0392B", pdf: rgb(0.99, 0.91, 0.91), dot: rgb(0.75, 0.22, 0.17) },
  High: { bg: "FFFEF3E2", fg: "FFE67E22", pdf: rgb(0.99, 0.95, 0.89), dot: rgb(0.9, 0.5, 0.13) },
  Medium: { bg: "FFFFF9E6", fg: "FFF1C40F", pdf: rgb(1, 0.98, 0.9), dot: rgb(0.95, 0.77, 0.06) },
  Low: { bg: "FFE8F8F0", fg: "FF27AE60", pdf: rgb(0.91, 0.97, 0.94), dot: rgb(0.15, 0.69, 0.38) },
  Default: { bg: "FFF8F9FA", fg: "FF6C757D", pdf: rgb(0.97, 0.98, 0.99), dot: rgb(0.44, 0.46, 0.5) },
};

function getRiskStyle(value) {
  if (!value) return RISK_COLORS.Default;
  const str = String(value).toLowerCase();
  for (const [key, style] of Object.entries(RISK_COLORS)) {
    if (key === "Default") continue;
    if (str.includes(key.toLowerCase())) return style;
  }
  return RISK_COLORS.Default;
}

const ROLE_PERMISSIONS = {
  admin: ["admin.all"], board: ["admin.all"],
  ciso: ["policy.view", "compliance.view", "risk.view", "audit.view", "controls.view", "asset.view", "governance.view", "report.generate"],
  cro: ["risk.view", "governance.view", "compliance.view", "report.generate", "policy.view"],
  risk_owner: ["risk.view", "asset.view", "report.generate"],
  analyst: ["compliance.view", "risk.view", "report.generate"],
  viewer: ["report.generate"],
};

function getRolePermissions(role) { return ROLE_PERMISSIONS[role] || []; }

const registry = new Map();

export function registerReport(definition) {
  if (!definition.id || !definition.name || !definition.dataSource) {
    throw new Error(`Report definition must have id, name, and dataSource: ${definition.id || "unknown"}`);
  }
  registry.set(definition.id, {
    ...definition,
    columns: definition.columns || [],
    supportedFormats: definition.supportedFormats || ["xlsx", "pdf", "csv"],
    icon: definition.icon || "FileText",
    isDashboard: definition.isDashboard || false,
  });
}

export function getAllReports(moduleFilter) {
  const reports = Array.from(registry.values());
  if (moduleFilter && moduleFilter !== "all") return reports.filter((r) => r.module === moduleFilter);
  return reports;
}

export function getReportDefinition(reportId) { return registry.get(reportId); }

export async function generateReport(reportId, format, filters, user, context = {}) {
  const def = registry.get(reportId);
  if (!def) throw new Error(`Report not found: ${reportId}`);
  if (!def.supportedFormats.includes(format)) throw new Error(`Format "${format}" not supported`);
  if (def.requiredPermission && user) {
    const perms = getRolePermissions(user.role);
    if (!perms.includes(def.requiredPermission) && !perms.includes("admin.all")) {
      throw new Error(`Access denied: requires "${def.requiredPermission}"`);
    }
  }
  let rows = await def.dataSource(context);
  if (filters && Object.keys(filters).length > 0) rows = applyFilters(rows, filters);
  const meta = {
    title: def.name, module: def.module, generatedAt: new Date().toISOString(),
    generatedBy: user?.username || user?.fullName || "system", rowCount: rows.length,
    isDashboard: def.isDashboard, colorColumns: def.colorColumns || [],
  };
  switch (format) {
    case "xlsx": return renderXLSX(def.columns, rows, meta);
    case "pdf": return renderPDF(def.columns, rows, meta);
    case "csv": return renderCSV(def.columns, rows, meta);
    default: throw new Error(`Unknown format: ${format}`);
  }
}

function applyFilters(rows, filters) {
  return rows.filter((row) => {
    for (const [key, cond] of Object.entries(filters)) {
      const v = getNestedValue(row, key);
      if (cond.eq !== undefined && v !== cond.eq) return false;
      if (cond.neq !== undefined && v === cond.neq) return false;
      if (cond.in !== undefined && !cond.in.includes(v)) return false;
      if (cond.nin !== undefined && cond.nin.includes(v)) return false;
      if (cond.contains !== undefined && !String(v || "").toLowerCase().includes(String(cond.contains).toLowerCase())) return false;
      if (cond.gt !== undefined && !(v > cond.gt)) return false;
      if (cond.lt !== undefined && !(v < cond.lt)) return false;
      if (cond.gte !== undefined && !(v >= cond.gte)) return false;
      if (cond.lte !== undefined && !(v <= cond.lte)) return false;
      if (cond.after !== undefined && new Date(v) < new Date(cond.after)) return false;
      if (cond.before !== undefined && new Date(v) > new Date(cond.before)) return false;
    }
    return true;
  });
}

function getNestedValue(obj, path) { return path.split(".").reduce((acc, part) => acc?.[part], obj); }

function fmtVal(value, format) {
  if (value == null || value === "") return "—";
  switch (format) {
    case "date": return new Date(value).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
    case "datetime": return new Date(value).toLocaleString("en-GB", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" });
    case "currency": return Number(value).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    case "percent": return `${value}%`;
    default: return String(value);
  }
}

// ══════════════════════════════════════════════
// XLSX RENDERER — Enterprise Grade
// ══════════════════════════════════════════════

async function renderXLSX(columns, rows, meta) {
  const wb = new ExcelJS.Workbook();
  wb.creator = "WADJET GRC Platform";
  wb.created = new Date();
  const ws = wb.addWorksheet(meta.title.slice(0, 31));

  // Logo
  if (BRANDING.logoPath) {
    try {
      const ext = BRANDING.logoPath.toLowerCase().endsWith(".png") ? "png" : "jpeg";
      const logoId = wb.addImage({ filename: BRANDING.logoPath, extension: ext });
      ws.addImage(logoId, { tl: { col: 0, row: 0 }, ext: { width: 200, height: 60 } });
    } catch { /* optional */ }
  }

  // Title
  const titleRow = 5;
  ws.mergeCells(titleRow, 1, titleRow, Math.max(columns.length, 8));
  const titleCell = ws.getCell(titleRow, 1);
  titleCell.value = meta.title;
  titleCell.font = { size: 20, bold: true, color: { argb: "FF1A1A1A" }, name: "Calibri" };
  titleCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFFFFFFF" } };
  titleCell.alignment = { horizontal: "left", vertical: "middle" };
  ws.getRow(titleRow).height = 35;

  // Subtitle
  const subRow = titleRow + 1;
  ws.mergeCells(subRow, 1, subRow, Math.max(columns.length, 8));
  const subCell = ws.getCell(subRow, 1);
  subCell.value = `${BRANDING.footerText} | ${new Date(meta.generatedAt).toLocaleString("en-GB")} | Prepared by: ${meta.generatedBy} | ${meta.rowCount} records`;
  subCell.font = { size: 9, italic: true, color: { argb: "FF888888" }, name: "Calibri" };
  subCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFFFFFFF" } };

  // Dashboard KPI cards
  if (meta.isDashboard && rows.length > 0 && columns.length <= 3) {
    const kpiStart = subRow + 2;
    rows.forEach((row, i) => {
      const key = String(row[columns[0]?.key] || row.label || row.metric || row.name || Object.values(row)[0] || "");
      const val = String(row[columns[1]?.key] || row.value || row.score || row.percent || Object.values(row)[1] || "");
      const labelCell = ws.getCell(kpiStart + i, 1);
      labelCell.value = key;
      labelCell.font = { size: 11, bold: true, color: { argb: "FF2C3E50" }, name: "Calibri" };
      labelCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF8F9FA" } };
      labelCell.border = { bottom: { style: "thin", color: { argb: "FFDEE2E6" } } };
      const valCell = ws.getCell(kpiStart + i, 2);
      valCell.value = val;
      valCell.font = { size: 16, bold: true, color: { argb: `FF${PRIMARY_HEX}` }, name: "Calibri" };
      valCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF8F9FA" } };
      valCell.alignment = { horizontal: "right" };
      valCell.border = { bottom: { style: "thin", color: { argb: "FFDEE2E6" } } };
    });
    ws.getColumn(1).width = 50;
    ws.getColumn(2).width = 20;
  }

  const tableStart = meta.isDashboard && rows.length > 0 && columns.length <= 3
    ? subRow + 2 + rows.length + 2
    : subRow + 2;

  // Header
  const headerRow = ws.getRow(tableStart);
  columns.forEach((col, i) => {
    const cell = headerRow.getCell(i + 1);
    cell.value = col.header;
    cell.font = { bold: true, color: { argb: "FF1A1A1A" }, size: 10, name: "Calibri" };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: `FF${PRIMARY_HEX}` } };
    cell.alignment = { horizontal: "center", vertical: "middle", wrapText: true };
    cell.border = { bottom: { style: "medium", color: { argb: "FFB8860B" } }, top: { style: "thin", color: { argb: "FFDEE2E6" } }, left: { style: "thin", color: { argb: "FFDEE2E6" } }, right: { style: "thin", color: { argb: "FFDEE2E6" } } };
  });
  ws.getRow(tableStart).height = 28;

  // Data rows
  rows.forEach((row, ri) => {
    const excelRow = ws.getRow(tableStart + 1 + ri);
    excelRow.height = 20;
    const fillColor = ri % 2 === 0 ? "FFFFFFFF" : "FFF8F9FA";
    columns.forEach((col, ci) => {
      const raw = getNestedValue(row, col.key);
      const cell = excelRow.getCell(ci + 1);
      cell.value = col.format ? fmtVal(raw, col.format) : (raw ?? "—");
      cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: fillColor } };
      cell.font = { color: { argb: "FF2C3E50" }, size: 9, name: "Calibri" };
      cell.alignment = { vertical: "middle", wrapText: true };
      cell.border = { bottom: { style: "thin", color: { argb: "FFEBEEF0" } }, left: { style: "thin", color: { argb: "FFEBEEF0" } }, right: { style: "thin", color: { argb: "FFEBEEF0" } } };
      if (meta.colorColumns.includes(col.key)) {
        const style = getRiskStyle(raw);
        cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: style.bg } };
        cell.font = { color: { argb: style.fg }, size: 9, bold: true, name: "Calibri" };
      }
    });
  });

  // Auto-width
  columns.forEach((col, i) => {
    let maxLen = String(col.header).length + 3;
    for (let ri = 0; ri < Math.min(rows.length, 200); ri++) {
      const raw = getNestedValue(rows[ri], col.key);
      const val = col.format ? fmtVal(raw, col.format) : String(raw ?? "");
      maxLen = Math.max(maxLen, val.length + 3);
    }
    ws.getColumn(i + 1).width = Math.min(Math.max(maxLen, 12), 55);
  });

  ws.views = [{ state: "frozen", ySplit: tableStart }];

  // Watermark
  if (rows.length > 0) {
    const wmRow = tableStart + Math.min(rows.length, 10) + 3;
    ws.mergeCells(wmRow, 1, wmRow, Math.max(columns.length, 8));
    const wmCell = ws.getCell(wmRow, 1);
    wmCell.value = BRANDING.watermarkText;
    wmCell.font = { size: 36, color: { argb: "FFF0F0F0" }, italic: true, name: "Calibri" };
    wmCell.alignment = { horizontal: "center", vertical: "middle" };
  }

  return await wb.xlsx.writeBuffer();
}

// ══════════════════════════════════════════════
// PDF RENDERER — Enterprise Grade
// ══════════════════════════════════════════════

async function renderPDF(columns, rows, meta) {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const isWide = columns.length > 6;
  const pageW = isWide ? 1024 : 612;
  const pageH = isWide ? 612 : 792;
  const margin = isWide ? 30 : 40;
  const usableW = pageW - margin * 2;

  if (meta.isDashboard && columns.length <= 3) {
    await renderDashboardPDF(pdfDoc, columns, rows, meta, font, boldFont, pageW, pageH, margin, usableW);
  } else {
    await renderTablePDF(pdfDoc, columns, rows, meta, font, boldFont, pageW, pageH, margin, usableW, isWide);
  }

  return await pdfDoc.save();
}

async function renderDashboardPDF(pdfDoc, columns, rows, meta, font, boldFont, pageW, pageH, margin, usableW) {
  const page = pdfDoc.addPage([pageW, pageH]);
  let y = pageH - margin;

  // Executive masthead with a restrained, print-safe brand treatment.
  page.drawRectangle({ x: 0, y: pageH - 96, width: pageW, height: 96, color: DARK_BG });
  page.drawRectangle({ x: 0, y: pageH - 96, width: 8, height: 96, color: PRIMARY });

  if (BRANDING.logoPath) {
    try {
      const logoBytes = await readFileBytes(BRANDING.logoPath);
      const logo = await pdfDoc.embedPng(logoBytes);
      const scale = Math.min(0.34, 68 / logo.height);
      const dims = logo.scale(scale);
      page.drawImage(logo, { x: margin, y: pageH - 82, width: dims.width, height: dims.height });
    } catch { /* optional */ }
  }

  page.drawText("BOARD REPORT", { x: pageW - margin - 100, y: pageH - 38, size: 9, font: boldFont, color: PRIMARY });
  page.drawText("CONFIDENTIAL", { x: pageW - margin - 100, y: pageH - 55, size: 8, font, color: rgb(0.75, 0.75, 0.78) });
  y = pageH - 112;

  page.drawText(meta.title, { x: margin, y, size: 22, font: boldFont, color: rgb(0.1, 0.1, 0.1) });
  y -= 26;
  page.drawText("Executive decision support | current control and compliance posture", { x: margin, y, size: 8, font, color: rgb(0.42, 0.43, 0.46) });
  y -= 14;
  page.drawText(`${BRANDING.footerText} | ${new Date(meta.generatedAt).toLocaleString("en-GB")} | Prepared by: ${meta.generatedBy}`, { x: margin, y, size: 8, font, color: rgb(0.5, 0.5, 0.5) });
  y -= 8;
  page.drawLine({ start: { x: margin, y }, end: { x: pageW - margin, y }, thickness: 1.5, color: PRIMARY });
  y -= 30;

  // Watermark
  drawWatermark(page, font, pageW, pageH);

  // KPI bars
  const chartData = rows.map((r) => ({
    label: String(r[columns[0]?.key] || r.label || r.metric || r.name || Object.values(r)[0] || ""),
    value: parseFloat(r[columns[1]?.key] || r.value || r.score || r.percent || Object.values(r)[1]) || 0,
  })).filter((d) => d.label && !isNaN(d.value));

  if (chartData.length > 0) {
    const maxVal = Math.max(...chartData.map((d) => d.value), 1);
    const barH = 20;
    const barGap = 10;
    const labelW = 250;
    const barMaxW = usableW - labelW - 90;

    const average = Math.round(chartData.reduce((sum, item) => sum + item.value, 0) / chartData.length);
    const belowTarget = chartData.filter((item) => item.value < 80).length;
    const cardW = (usableW - 24) / 3;
    [["AVERAGE POSTURE", `${average}%`], ["FRAMEWORKS", String(chartData.length)], ["BELOW 80% TARGET", String(belowTarget)]].forEach(([label, value], index) => {
      const x = margin + index * (cardW + 12);
      page.drawRectangle({ x, y: y - 50, width: cardW, height: 50, color: index === 2 && belowTarget > 0 ? rgb(0.99, 0.96, 0.9) : rgb(0.96, 0.96, 0.97), borderColor: rgb(0.88, 0.88, 0.9), borderWidth: 0.7 });
      page.drawText(label, { x: x + 9, y: y - 15, size: 7, font: boldFont, color: rgb(0.42, 0.43, 0.46) });
      page.drawText(value, { x: x + 9, y: y - 37, size: 16, font: boldFont, color: index === 2 && belowTarget > 0 ? rgb(0.72, 0.37, 0.05) : rgb(0.08, 0.08, 0.1) });
    });
    y -= 64;
    page.drawText("POSTURE BY FRAMEWORK", { x: margin, y, size: 11, font: boldFont, color: rgb(0.1, 0.1, 0.1) });
    y -= 28;

    chartData.forEach((item) => {
      page.drawText(item.label.slice(0, 45), { x: margin, y: y - 4, size: 8, font, color: rgb(0.3, 0.3, 0.3) });
      page.drawRectangle({ x: margin + labelW, y: y - barH + 2, width: barMaxW, height: barH - 4, color: rgb(0.95, 0.95, 0.96) });
      page.drawRectangle({ x: margin + labelW, y: y - barH + 2, width: Math.max((item.value / maxVal) * barMaxW, 4), height: barH - 4, color: PRIMARY });
      page.drawText(String(item.value), { x: margin + labelW + barMaxW + 10, y: y - 4, size: 10, font: boldFont, color: PRIMARY });
      y -= barH + barGap;
    });
  }

  y -= 20;
  page.drawLine({ start: { x: margin, y }, end: { x: pageW - margin, y }, thickness: 0.5, color: rgb(0.85, 0.85, 0.85) });
  y -= 20;

  // Table
  const colW = usableW / columns.length;
  let x = margin;
  columns.forEach((col) => {
    page.drawRectangle({ x, y: y - 22, width: colW, height: 22, color: PRIMARY });
    page.drawText(col.header.slice(0, 40), { x: x + 4, y: y - 14, size: 7, font: boldFont, color: rgb(0.1, 0.1, 0.1) });
    x += colW;
  });
  y -= 22;

  const maxTableRows = Math.floor((y - margin - 30) / 14);
  rows.slice(0, maxTableRows).forEach((row, ri) => {
    x = margin;
    columns.forEach((col) => {
      const raw = getNestedValue(row, col.key);
      const text = (col.format ? fmtVal(raw, col.format) : String(raw ?? "—")).slice(0, 45);
      if (ri % 2 === 0) page.drawRectangle({ x, y: y - 14, width: colW, height: 14, color: rgb(0.98, 0.98, 0.99) });
      page.drawText(text, { x: x + 4, y: y - 9, size: 7, font, color: rgb(0.15, 0.15, 0.15) });
      x += colW;
    });
    y -= 14;
  });

  page.drawText(BRANDING.footerText, { x: margin, y: margin + 12, size: 7, font, color: rgb(0.5, 0.5, 0.5) });
  page.drawText("Page 1 of 1", { x: pageW - margin - 50, y: margin + 12, size: 7, font, color: rgb(0.5, 0.5, 0.5) });
}

async function renderTablePDF(pdfDoc, columns, rows, meta, font, boldFont, pageW, pageH, margin, usableW, isWide) {
  const fontSize = isWide ? 6 : 7;
  const headerH = isWide ? 24 : 28;
  const rowH = isWide ? 13 : 15;
  const colW = usableW / columns.length;
  const tableBottom = margin + (isWide ? 25 : 35);
  const headerBlockH = isWide ? 90 : 100;
  const tableTop = pageH - margin - headerBlockH;
  const rowsPerPage = Math.floor((tableTop - tableBottom) / rowH);

  let pageIndex = 0;
  let rowIndex = 0;

  while (rowIndex < rows.length || pageIndex === 0) {
    const page = pdfDoc.addPage([pageW, pageH]);
    let y = pageH - margin;

    // Header bar
    page.drawRectangle({ x: 0, y: pageH - 75, width: pageW, height: 75, color: rgb(0.98, 0.98, 0.99) });
    page.drawLine({ start: { x: 0, y: pageH - 75 }, end: { x: pageW, y: pageH - 75 }, thickness: 2.5, color: PRIMARY });

    if (BRANDING.logoPath) {
      try {
        const logoBytes = await readFileBytes(BRANDING.logoPath);
        const logo = await pdfDoc.embedPng(logoBytes);
        const scale = isWide ? 0.3 : 0.4;
        const dims = logo.scale(scale);
        page.drawImage(logo, { x: margin, y: pageH - margin - dims.height + 10, width: dims.width, height: dims.height });
      } catch { /* optional */ }
    }

    page.drawText("WADJET GRC", { x: pageW - margin - 110, y: pageH - margin - 8, size: isWide ? 12 : 16, font: boldFont, color: PRIMARY });
    y = pageH - 85;

    page.drawText(meta.title, { x: margin, y, size: isWide ? 16 : 20, font: boldFont, color: rgb(0.1, 0.1, 0.1) });
    y -= isWide ? 18 : 22;
    page.drawText(`${BRANDING.footerText} | ${new Date(meta.generatedAt).toLocaleString("en-GB")} | Prepared by: ${meta.generatedBy} | ${meta.rowCount} records`, { x: margin, y, size: isWide ? 6 : 8, font, color: rgb(0.5, 0.5, 0.5) });
    y -= 6;
    page.drawLine({ start: { x: margin, y }, end: { x: pageW - margin, y }, thickness: 1, color: PRIMARY });
    y -= 10;

    // Watermark
    drawWatermark(page, font, pageW, pageH);

    // Header row
    let x = margin;
    columns.forEach((col) => {
      page.drawRectangle({ x, y: y - headerH, width: colW, height: headerH, color: PRIMARY });
      page.drawText(col.header.slice(0, 45), { x: x + 3, y: y - headerH + 7, size: fontSize, font: boldFont, color: rgb(0.1, 0.1, 0.1) });
      x += colW;
    });
    y -= headerH;

    // Data rows
    const pageRows = rows.slice(rowIndex, rowIndex + rowsPerPage);
    pageRows.forEach((row, ri) => {
      x = margin;
      columns.forEach((col, ci) => {
        const raw = getNestedValue(row, col.key);
        const text = (col.format ? fmtVal(raw, col.format) : String(raw ?? "—")).slice(0, 50);
        const isColorCol = meta.colorColumns.includes(col.key);
        if (isColorCol) {
          const style = getRiskStyle(raw);
          page.drawRectangle({ x, y: y - rowH, width: colW, height: rowH, color: style.pdf });
        } else if (ri % 2 === 0) {
          page.drawRectangle({ x, y: y - rowH, width: colW, height: rowH, color: rgb(0.98, 0.98, 0.99) });
        }
        page.drawText(text, { x: x + 3, y: y - 9, size: fontSize, font, color: rgb(0.15, 0.15, 0.15) });
        x += colW;
      });
      y -= rowH;
      rowIndex++;
    });

    const totalPages = Math.max(1, Math.ceil(rows.length / rowsPerPage));
    page.drawText(BRANDING.footerText, { x: margin, y: margin + 10, size: 7, font, color: rgb(0.5, 0.5, 0.5) });
    page.drawText(`Page ${pageIndex + 1} of ${totalPages}`, { x: pageW - margin - 60, y: margin + 10, size: 7, font, color: rgb(0.5, 0.5, 0.5) });

    if (rowIndex >= rows.length) break;
    pageIndex++;
  }
}

function drawWatermark(page, font, pageW, pageH) {
  const text = BRANDING.watermarkText;
  const fontSize = pageW > 700 ? 46 : 56;
  const textWidth = font.widthOfTextAtSize(text, fontSize);
  page.drawText(text, {
    x: pageW / 2 - textWidth / 2, y: pageH / 2 + 70, size: fontSize, font, color: PRIMARY, opacity: 0.06, rotate: degrees(45),
  });
}

async function readFileBytes(filePath) {
  const fs = await import("node:fs/promises");
  return fs.readFile(filePath);
}

// ══════════════════════════════════════════════
// CSV RENDERER
// ══════════════════════════════════════════════

async function renderCSV(columns, rows, meta) {
  const BOM = "﻿";
  const escape = (v) => `"${String(v ?? "").replace(/"/g, '""')}"`;
  const headerRow = columns.map((c) => escape(c.header)).join(",");
  const dataRows = rows.map((row) => columns.map((col) => {
    const raw = getNestedValue(row, col.key);
    return escape(col.format ? fmtVal(raw, col.format) : (raw ?? ""));
  }).join(","));
  const metaRows = [
    `# ${BRANDING.footerText}`,
    `# Report: ${meta.title} | Generated: ${new Date(meta.generatedAt).toLocaleString("en-GB")} | By: ${meta.generatedBy} | Rows: ${meta.rowCount}`,
  ];
  return Buffer.from(BOM + [...metaRows, headerRow, ...dataRows].join("\n"), "utf-8");
}

export default { registerReport, getAllReports, getReportDefinition, generateReport, BRANDING };
