import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router";
import { AlertTriangle, Check, ChevronRight, FileUp, ShieldCheck } from "lucide-react";
import api, { resource } from "../../api/client";
import PageHeader from "../../components/PageHeader";
import Modal from "../../components/Modal";
import { Field, Select, TextArea, TextInput } from "../../components/Field";
import { ErrorState, LoadingState } from "../../components/States";
import RiskLifecycleStepper from "../../components/RiskLifecycleStepper";
import { withRiskParam } from "../../lib/riskLifecycle";

const risksApi = resource("risks"), usersApi = resource("users"), controlsApi = resource("controls"), vendorsApi = resource("third-party"), assetsApi = resource("assets");
const strategies = [
  { id: "MODIFY", title: "Modify", sub: "Risk reduction", detail: "Apply selected ISO 27002 controls." },
  { id: "RETAIN", title: "Retain", sub: "Risk acceptance", detail: "Accept with documented justification." },
  { id: "AVOID", title: "Avoid", sub: "Stop exposure", detail: "Retire the activity or asset." },
  { id: "SHARE", title: "Share", sub: "Transfer", detail: "Transfer exposure through a vendor or insurance." },
];
const scoreTone = (score) => score <= 4 ? "border-emerald-800/70 bg-emerald-950/40 text-emerald-300" : score <= 10 ? "border-amber-800/70 bg-amber-950/40 text-amber-300" : "border-red-800/70 bg-red-950/40 text-red-300";
const inherentScore = (risk) => Number(risk?.riskScore || risk?.inherentScore || 0);

function Score({ label, value }) { return <div className={`rounded-lg border px-4 py-3 ${scoreTone(value)}`}><p className="text-[10px] uppercase tracking-[.16em] opacity-70">{label}</p><p className="heading mt-1 text-2xl">{value || "—"}</p></div>; }
function Matrix({ likelihood, impact, onChange }) {
  return <div className="grid grid-cols-[auto_repeat(5,minmax(0,1fr))] gap-1.5 text-center"><span className="p-2 text-[10px] text-neutral-500">L \ I</span>{[1,2,3,4,5].map((i) => <span className="p-2 text-xs text-neutral-500" key={i}>{i}</span>)}{[5,4,3,2,1].map((l) => <div className="contents" key={l}><span className="p-2 text-xs text-neutral-500">{l}</span>{[1,2,3,4,5].map((i) => <button type="button" key={`${l}-${i}`} onClick={() => onChange(l, i)} className={`min-h-10 rounded border text-xs font-semibold ${scoreTone(l * i)} ${l === likelihood && i === impact ? "ring-2 ring-gold ring-offset-2 ring-offset-ink" : "opacity-75 hover:opacity-100"}`}>{l * i}</button>)}</div>)}</div>;
}

export default function RiskTreatment() {
  const [searchParams] = useSearchParams();
  const linkedRiskId = searchParams.get("riskId");
  const [data, setData] = useState({ risks: [], users: [], controls: [], vendors: [], assets: [] });
  const [treatments, setTreatments] = useState([]), [selectedTreatment, setSelectedTreatment] = useState(null);
  const [loading, setLoading] = useState(true), [error, setError] = useState(""), [notice, setNotice] = useState(""), [avoidModal, setAvoidModal] = useState(false), [avoidConfirmed, setAvoidConfirmed] = useState(false), [search, setSearch] = useState(""), [treatmentId, setTreatmentId] = useState("");
  const [approvalDialog, setApprovalDialog] = useState({ open: false, treatment: null, decision: "APPROVED", comment: "" });
  const [evidenceDialog, setEvidenceDialog] = useState({ open: false, treatment: null, name: "", reference: "" });
  const [reviewDialog, setReviewDialog] = useState({ open: false, treatment: null, score: "80" });
  const [form, setForm] = useState({ risk_id: "", strategy: "MODIFY", justification: "", residual_likelihood: 1, residual_impact: 1, owner_id: "", target_date: "", allocated_budget: "", progress_percentage: 0, control_ids: [], vendor_id: "", attachment_name: "", asset_id: "" });
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const load = () => { setLoading(true); setError(""); Promise.all([risksApi.list({ pageSize: 200 }), usersApi.list({ pageSize: 200 }), controlsApi.list({ pageSize: 500 }), vendorsApi.list({ pageSize: 200 }), assetsApi.list({ pageSize: 200 }), api.get("/v1/treatments")]).then(([risks, users, controls, vendors, assets, treatmentData]) => { setData({ risks: risks.items || [], users: users.items || [], controls: controls.items || [], vendors: vendors.items || [], assets: assets.items || [] }); setTreatments(treatmentData.data.items || []); }).catch((err) => setError(err?.response?.data?.message || err.message)).finally(() => setLoading(false)); };
  useEffect(load, []);
  const risk = data.risks.find((item) => item._id === form.risk_id), inherent = inherentScore(risk), residual = Number(form.residual_likelihood) * Number(form.residual_impact);
  const shownControls = useMemo(() => data.controls.filter((item) => `${item.controlId} ${item.annexCode} ${item.name} ${item.category}`.toLowerCase().includes(search.toLowerCase())), [data.controls, search]);
  const selectRisk = (id) => { const selected = data.risks.find((item) => item._id === id); update("risk_id", id); if (selected) { update("residual_likelihood", Math.min(5, Number(selected.likelihood) || 1)); update("residual_impact", Math.min(5, Number(selected.impactScore) || 1)); update("asset_id", selected.asset?._id || ""); update("target_date", String(selected.treatmentDueDate || selected.deadline || "").slice(0, 10)); } };
  useEffect(() => {
    if (linkedRiskId && data.risks.length && !form.risk_id) {
      selectRisk(linkedRiskId);
    }
  }, [data.risks, linkedRiskId]);
  const toggleControl = (id) => update("control_ids", form.control_ids.includes(id) ? form.control_ids.filter((item) => item !== id) : [...form.control_ids, id]);
  const currentUser = (() => { try { return JSON.parse(localStorage.getItem("wadjet_user") || "null"); } catch { return null; } })();
  const canApproveTreatment = (treatment) => ["cro", "board", "ciso"].includes(currentUser?.role) && treatment?.owner_id !== currentUser?._id;
  const submit = async (event) => { event.preventDefault(); setError(""); setNotice(""); if (!risk) return setError("Select a registered risk."); if (residual > inherent) return setError("Residual score cannot exceed inherent score."); if (form.strategy === "MODIFY" && !form.control_ids.length) return setError("At least one ISO 27002 control is required."); if (!form.justification.trim()) return setError("Justification is required."); if (form.strategy === "SHARE" && !form.vendor_id) return setError("Select the third-party vendor."); if (form.strategy === "AVOID" && !avoidConfirmed) return setAvoidModal(true); try { const response = await api.post(`/v1/risks/${risk._id}/treatments`, { ...form, residual_likelihood: Number(form.residual_likelihood), residual_impact: Number(form.residual_impact), allocated_budget: Number(form.allocated_budget || 0) }); setTreatmentId(response.data._id); setNotice(response.data.approval_required ? "Treatment submitted as Proposed and escalated to the CRO / Risk Committee." : "Treatment saved as Draft."); } catch (err) { setError(err?.response?.data?.message || err.message); } };
  const saveProgress = async () => { if (!treatmentId) return setError("Save the treatment plan before updating progress."); try { const response = await api.patch(`/v1/treatments/${treatmentId}/progress`, { progress_percentage: Number(form.progress_percentage) }); setNotice(response.data.status === "COMPLETED" ? "Treatment implementation is complete; independent effectiveness review is required before closure monitoring." : "Treatment progress updated."); load(); } catch (err) { setError(err?.response?.data?.message || err.message); } };
  const transition = async (treatment, endpoint, body = {}) => { try { const response = await api.post(`/v1/treatments/${treatment._id}/${endpoint}`, body); setSelectedTreatment(response.data); setNotice(`Treatment ${endpoint.replace("-", " ")} recorded.`); load(); } catch (err) { setError(err?.response?.data?.message || err.message); } };
  if (loading) return <LoadingState label="Loading risk-treatment workspace…" />;
  if (error && !data.risks.length) return <ErrorState message={error} onRetry={load} />;
  return <><PageHeader title="Risk Treatment" subtitle="ISO/IEC 27005 treatment planning with manual ISO 27002 control selection." actions={<div className="flex items-center gap-3"><RiskLifecycleStepper current="treatment" riskId={linkedRiskId || undefined} />{linkedRiskId ? <div className="flex items-center gap-3 text-xs"><a className="text-gold hover:underline" href={withRiskParam("/risk/scoring", linkedRiskId)}>Score</a><a className="text-gold hover:underline" href={withRiskParam("/risk/reviews", linkedRiskId)}>Review</a><a className="text-gold hover:underline" href={withRiskParam("/risk/poam", linkedRiskId)}>POAM</a></div> : null}</div>} />
    <form className="mx-auto max-w-7xl space-y-6" onSubmit={submit}>
      {error && <div className="rounded-lg border border-red-800/70 bg-red-950/40 px-4 py-3 text-sm text-red-200">{error}</div>}{notice && <div className="rounded-lg border border-emerald-800/70 bg-emerald-950/40 px-4 py-3 text-sm text-emerald-200">{notice}</div>}
      {linkedRiskId && risk && <div className="rounded-lg border border-gold/40 bg-gold/10 px-4 py-3 text-sm text-gold">ISO 27005 treatment workflow: {risk.riskId || risk._id.slice(-6)} — {risk.title}. Continue from scoring through review, POAM and closure.</div>}
      <section className="card p-5"><div className="grid gap-4 md:grid-cols-2"><Field label="Risk to treat"><Select value={form.risk_id} onChange={(e) => selectRisk(e.target.value)} options={[{ value: "", label: "Select a registered risk" }, ...data.risks.map((item) => ({ value: item._id, label: `${item.riskId} — ${item.title}` }))]} /></Field>{risk && <div className="flex items-end gap-3"><Score label="Inherent risk" value={inherent} /><Score label="Residual risk" value={residual} /></div>}</div></section>
      <section className="card p-5"><h2 className="heading text-base font-semibold">1. Select treatment strategy</h2><p className="mt-1 text-xs text-neutral-500">Choose one of the four ISO 27005 treatment options.</p><div className="mt-4 grid gap-3 md:grid-cols-4">{strategies.map((item) => <button type="button" key={item.id} onClick={() => update("strategy", item.id)} className={`rounded-xl border p-4 text-left ${form.strategy === item.id ? "border-gold bg-gold/10 ring-1 ring-gold/50" : "border-line bg-white/[.015] hover:border-neutral-600"}`}><p className="heading text-sm">{item.title}</p><p className="mt-1 text-xs text-gold">{item.sub}</p><p className="mt-3 text-xs leading-5 text-neutral-500">{item.detail}</p></button>)}</div></section>
      <section className="grid gap-6 xl:grid-cols-[1fr_1.15fr]"><div className="card p-5"><h2 className="heading text-base font-semibold">2. Residual risk matrix</h2><p className="mt-1 text-xs text-neutral-500">Select remaining likelihood and impact after treatment.</p><div className="mt-5"><Matrix likelihood={Number(form.residual_likelihood)} impact={Number(form.residual_impact)} onChange={(likelihood, impact) => { update("residual_likelihood", likelihood); update("residual_impact", impact); }} /></div>{risk && residual > inherent && <p className="mt-4 flex gap-2 text-xs text-red-300"><AlertTriangle className="h-4 w-4" /> Residual score cannot exceed inherent score ({inherent}).</p>}</div><div className="card p-5"><h2 className="heading text-base font-semibold">3. Action plan & progress</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Treatment owner"><Select value={form.owner_id} onChange={(e) => update("owner_id", e.target.value)} options={[{ value: "", label: "Select owner" }, ...data.users.map((item) => ({ value: item._id, label: item.name || item.fullName }))]} /></Field><Field label="Target completion date"><TextInput required type="date" value={form.target_date} onChange={(e) => update("target_date", e.target.value)} /></Field><Field label="Allocated budget"><TextInput type="number" min="0" step="0.01" placeholder="0.00" value={form.allocated_budget} onChange={(e) => update("allocated_budget", e.target.value)} /></Field><Field label={`Progress — ${form.progress_percentage}%`} hint="Update is persisted after the plan is saved."><input className="mt-2 w-full accent-gold" type="range" min="0" max="100" value={form.progress_percentage} onChange={(e) => update("progress_percentage", Number(e.target.value))} onMouseUp={saveProgress} /></Field></div></div></section>
      {form.strategy === "MODIFY" && <section className="card p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="heading text-base font-semibold">Manual ISO 27002 control picker</h2><p className="mt-1 text-xs text-neutral-500">Search the stored control library and select controls manually. AI/RAG is disabled.</p></div><TextInput placeholder="Search control ID, Annex, title…" value={search} onChange={(e) => setSearch(e.target.value)} /></div><div className="mt-4 grid max-h-72 gap-2 overflow-y-auto md:grid-cols-2">{shownControls.map((control) => <label key={control._id} className={`flex cursor-pointer gap-3 rounded-lg border p-3 ${form.control_ids.includes(control._id) ? "border-gold/70 bg-gold/5" : "border-line"}`}><input type="checkbox" className="mt-1 accent-gold" checked={form.control_ids.includes(control._id)} onChange={() => toggleControl(control._id)} /><span><span className="font-mono text-xs text-gold">{control.annexCode || control.controlId}</span><span className="ml-2 text-sm text-neutral-200">{control.name}</span><span className="mt-1 block text-xs text-neutral-500">{control.category}</span></span></label>)}</div><p className="mt-3 text-xs text-emerald-300">{form.control_ids.length ? <><Check className="mr-1 inline h-3.5 w-3.5" />{form.control_ids.length} manual control(s) selected.</> : "Select at least one control for Modify."}</p></section>}
      {form.strategy === "RETAIN" && residual > 9 && <div className="rounded-lg border border-amber-800/70 bg-amber-950/40 px-4 py-3 text-sm text-amber-200"><AlertTriangle className="mr-2 inline h-4 w-4" />Residual score exceeds appetite (9): the plan will be proposed for formal CRO / Risk Committee approval.</div>}
      {form.strategy === "AVOID" && <section className="card border-red-800/50 p-5"><h2 className="heading text-base">Avoidance action</h2><p className="mt-1 text-xs text-neutral-500">The selected asset will be set to Inactive on plan submission.</p><div className="mt-4 max-w-md"><Field label="Associated asset"><Select value={form.asset_id} onChange={(e) => update("asset_id", e.target.value)} options={[{ value: "", label: "Select asset to inactivate" }, ...data.assets.map((item) => ({ value: item._id, label: item.name }))]} /></Field></div></section>}
      {form.strategy === "SHARE" && <section className="card p-5"><h2 className="heading text-base">Transfer arrangement</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Third-party vendor"><Select value={form.vendor_id} onChange={(e) => update("vendor_id", e.target.value)} options={[{ value: "", label: "Select vendor" }, ...data.vendors.map((item) => ({ value: item._id, label: item.name || item.vendorName }))]} /></Field><Field label="Insurance / SLA attachment"><label className="input flex cursor-pointer items-center gap-2"><FileUp className="h-4 w-4 text-gold" /><span className="truncate text-sm text-neutral-400">{form.attachment_name || "Choose file"}</span><input type="file" className="sr-only" onChange={(e) => update("attachment_name", e.target.files?.[0]?.name || "")} /></label></Field></div></section>}
      <section className="card p-5"><Field label="Treatment justification"><TextArea required placeholder="Document the rationale, acceptance conditions and implementation approach…" value={form.justification} onChange={(e) => update("justification", e.target.value)} /></Field></section><div className="flex justify-end"><button className="btn-primary inline-flex items-center gap-2" type="submit"><ShieldCheck className="h-4 w-4" />Save treatment plan <ChevronRight className="h-4 w-4" /></button></div>
    </form>
    <section className="card mx-auto mt-6 max-w-7xl overflow-hidden"><div className="border-b border-line px-5 py-4"><h2 className="heading text-base">Treatment register</h2><p className="mt-1 text-xs text-neutral-500">Open a treatment to review its approval history, action plan and evidence.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b border-line text-[10px] uppercase tracking-[.14em] text-neutral-500"><tr><th className="px-4 py-3">Risk</th><th className="px-4 py-3">Strategy</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Owner</th><th className="px-4 py-3">Target</th><th className="px-4 py-3">Evidence</th><th className="px-4 py-3" /></tr></thead><tbody className="divide-y divide-line">{treatments.map((treatment) => <tr key={treatment._id} className="hover:bg-white/[.025]"><td className="px-4 py-3 text-neutral-200">{treatment.risk?.riskId || treatment.risk_id}<span className="ml-2 text-xs text-neutral-500">{treatment.risk?.title}</span></td><td className="px-4 py-3 text-gold">{treatment.strategy}</td><td className="px-4 py-3"><span className={`chip ${treatment.status === "APPROVED" ? "border-emerald-800/70 bg-emerald-950/40 text-emerald-300" : treatment.status === "REJECTED" ? "border-red-800/70 bg-red-950/40 text-red-300" : "border-amber-800/70 bg-amber-950/40 text-amber-300"}`}>{treatment.workflow_status || treatment.status}{treatment.overdue_flag || treatment.overdue ? " · Overdue" : ""}</span></td><td className="px-4 py-3 text-neutral-400">{treatment.owner?.name || treatment.owner_id}</td><td className="px-4 py-3 text-neutral-400">{treatment.target_date || "—"}</td><td className="px-4 py-3 text-neutral-400">{treatment.evidence?.length || 0}</td><td className="px-4 py-3 text-right"><button type="button" className="text-xs text-gold" onClick={() => setSelectedTreatment(treatment)}>Review</button>{treatment.status === "DRAFT" && <button type="button" className="ml-3 text-xs text-gold" onClick={() => transition(treatment, "submit")}>Submit</button>}{treatment.status === "PROPOSED" && canApproveTreatment(treatment) && <button type="button" className="ml-3 text-xs text-emerald-300" onClick={() => setApprovalDialog({ open: true, treatment, decision: "APPROVED", comment: "" })}>Approve</button>}</td></tr>)}</tbody></table>{!treatments.length && <p className="p-8 text-center text-sm text-neutral-500">No treatment plans have been created.</p>}</div></section>
    <Modal open={Boolean(selectedTreatment)} onClose={() => setSelectedTreatment(null)} title="Treatment governance record" subtitle={selectedTreatment?.risk?.title || selectedTreatment?.risk_id} width="max-w-3xl"><div className="grid gap-3 sm:grid-cols-3"><Score label="Inherent" value={inherentScore(selectedTreatment?.risk)} /><Score label="Residual" value={selectedTreatment?.residual_score} /><Score label="Progress" value={`${selectedTreatment?.progress_percentage || 0}%`} /></div><div className="mt-5 grid gap-5 md:grid-cols-2"><div><h3 className="heading text-sm">Manual ISO 27002 controls</h3>{selectedTreatment?.controls?.map((item) => <p className="mt-2 text-xs text-neutral-400" key={item.control_id}>{item.control?.annexCode || item.control?.controlId} — {item.control?.name} <span className="text-gold">{item.implementation_status}</span></p>) || <p className="mt-2 text-xs text-neutral-500">None</p>}</div><div><h3 className="heading text-sm">Evidence & audit trail</h3><p className="mt-2 text-xs text-neutral-400">{selectedTreatment?.evidence?.length || 0} evidence item(s) · {selectedTreatment?.audit_events?.length || 0} immutable workflow event(s)</p>{selectedTreatment?.audit_events?.slice(0, 4).map((item) => <p className="mt-1 text-xs text-neutral-500" key={item._id}>{item.action} — {String(item.occurred_at).slice(0, 10)}</p>)}</div></div><div className="mt-5 flex flex-wrap gap-2">{selectedTreatment?.status === "APPROVED" && <button type="button" className="btn-secondary" onClick={() => setEvidenceDialog({ open: true, treatment: selectedTreatment, name: "", reference: "" })}>Add evidence</button>}{selectedTreatment?.status === "APPROVED" && <button type="button" className="btn-secondary" onClick={() => transition(selectedTreatment, "acknowledge")}>Acknowledge</button>}{selectedTreatment && <button type="button" className="btn-secondary" onClick={() => transition(selectedTreatment, "reminder")}>Send reminder</button>}{selectedTreatment?.status === "COMPLETED" && <button type="button" className="btn-primary" onClick={() => setReviewDialog({ open: true, treatment: selectedTreatment, score: "80" })}>Request effectiveness review</button>}</div></Modal>
    <Modal open={approvalDialog.open} onClose={() => setApprovalDialog({ open: false, treatment: null, decision: "APPROVED", comment: "" })} title="Approve treatment" subtitle={approvalDialog.treatment?.risk?.title || approvalDialog.treatment?.risk_id} width="max-w-md"><div className="space-y-4"><Field label="Decision"><Select value={approvalDialog.decision} onChange={(e) => setApprovalDialog((current) => ({ ...current, decision: e.target.value }))} options={[{ value: "APPROVED", label: "Approved" }, { value: "REJECTED", label: "Rejected" }]} /></Field><Field label="Decision comment"><TextArea rows={4} value={approvalDialog.comment} onChange={(e) => setApprovalDialog((current) => ({ ...current, comment: e.target.value }))} placeholder="Document the approval decision and conditions…" /></Field></div><div className="mt-5 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={() => setApprovalDialog({ open: false, treatment: null, decision: "APPROVED", comment: "" })}>Cancel</button><button type="button" className="btn-primary" onClick={() => { if (!approvalDialog.comment.trim()) return setError("Decision comment is required."); transition(approvalDialog.treatment, "decision", { decision: approvalDialog.decision, comment: approvalDialog.comment.trim() }); setApprovalDialog({ open: false, treatment: null, decision: "APPROVED", comment: "" }); }}>Submit decision</button></div></Modal>
    <Modal open={evidenceDialog.open} onClose={() => setEvidenceDialog({ open: false, treatment: null, name: "", reference: "" })} title="Add treatment evidence" subtitle={evidenceDialog.treatment?.risk?.title || evidenceDialog.treatment?.risk_id} width="max-w-md"><div className="space-y-4"><Field label="Evidence name"><TextInput value={evidenceDialog.name} onChange={(e) => setEvidenceDialog((current) => ({ ...current, name: e.target.value }))} placeholder="e.g. Firewall change log" /></Field><Field label="Immutable reference / URL"><TextInput value={evidenceDialog.reference} onChange={(e) => setEvidenceDialog((current) => ({ ...current, reference: e.target.value }))} placeholder="https://example.com/… or document ID" /></Field></div><div className="mt-5 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={() => setEvidenceDialog({ open: false, treatment: null, name: "", reference: "" })}>Cancel</button><button type="button" className="btn-primary" onClick={() => { if (!evidenceDialog.name.trim() || !evidenceDialog.reference.trim()) return setError("Evidence name and reference are required."); transition(evidenceDialog.treatment, "evidence", { name: evidenceDialog.name.trim(), reference: evidenceDialog.reference.trim() }); setEvidenceDialog({ open: false, treatment: null, name: "", reference: "" }); }}>Save evidence</button></div></Modal>
    <Modal open={reviewDialog.open} onClose={() => setReviewDialog({ open: false, treatment: null, score: "80" })} title="Request effectiveness review" subtitle={reviewDialog.treatment?.risk?.title || reviewDialog.treatment?.risk_id} width="max-w-md"><div className="space-y-4"><Field label="Validated control effectiveness (%)"><TextInput type="number" min="80" max="100" value={reviewDialog.score} onChange={(e) => setReviewDialog((current) => ({ ...current, score: e.target.value }))} /></Field></div><div className="mt-5 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={() => setReviewDialog({ open: false, treatment: null, score: "80" })}>Cancel</button><button type="button" className="btn-primary" onClick={() => { const score = Number(reviewDialog.score || 80); if (Number.isNaN(score) || score < 80) return setError("Effectiveness review score must be at least 80%."); transition(reviewDialog.treatment, "effectiveness-review", { control_effectiveness: { validated_controls: score } }); setReviewDialog({ open: false, treatment: null, score: "80" }); }}>Submit review</button></div></Modal>
    <Modal open={avoidModal} onClose={() => setAvoidModal(false)} title="Set asset inactive?" subtitle="This is a controlled avoidance action." footer={<><button type="button" className="btn-secondary" onClick={() => setAvoidModal(false)}>Cancel</button><button type="button" className="btn-primary" onClick={() => { setAvoidConfirmed(true); setAvoidModal(false); }}>Confirm avoidance</button></>}><p className="text-sm text-neutral-300">The asset will be marked <strong>Inactive</strong> when this treatment is submitted.</p></Modal>
  </>;
}
